"""
Trading Signal Model - Stores LLM-generated trading signals.
"""
from sqlalchemy import Column, Integer, String, Float, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from backend.core.database import Base


class TradingSignal(Base):
    """Model for storing trading signals generated by LLM analysis."""
    
    __tablename__ = "trading_signals"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # Symbol and strategy
    symbol = Column(String(50), nullable=False, index=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"), nullable=True)
    
    # Signal details
    signal_type = Column(String(10), nullable=False)  # BUY, SELL, HOLD
    trend = Column(String(20), nullable=True)  # strong_bullish, bullish, neutral, bearish, strong_bearish
    confidence = Column(Float, nullable=True)  # 0.0 to 1.0
    
    # Timeframes
    timeframe_primary = Column(String(10), nullable=False, default="1d")
    timeframe_confirmation = Column(String(10), nullable=True, default="1w")
    
    # Trading parameters
    entry_price_low = Column(Float, nullable=True)
    entry_price_high = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    target_conservative = Column(Float, nullable=True)
    target_aggressive = Column(Float, nullable=True)
    r_multiple_conservative = Column(Float, nullable=True)
    r_multiple_aggressive = Column(Float, nullable=True)
    position_size_percent = Column(Float, nullable=True)
    
    # Signal confirmation (3/4 rule)
    confirmation_signals = Column(JSON, nullable=True)  # {supertrend, price_vs_ma20, macd, rsi, confirmed_count, passed}
    
    # Analysis text
    analysis_daily = Column(Text, nullable=True)
    analysis_weekly = Column(Text, nullable=True)
    analysis_consolidated = Column(Text, nullable=True)
    
    # Chart URLs
    chart_url_daily = Column(String(500), nullable=True)
    chart_url_weekly = Column(String(500), nullable=True)
    chart_html_daily = Column(String(500), nullable=True)
    chart_html_weekly = Column(String(500), nullable=True)
    
    # Metadata
    language = Column(String(5), nullable=False, default="en")
    model_used = Column(String(50), nullable=True)
    provider = Column(String(20), nullable=True)
    
    # Timestamps
    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    
    # Status tracking
    status = Column(String(20), nullable=False, default="active")  # active, expired, executed, cancelled
    execution_price = Column(Float, nullable=True)
    execution_time = Column(DateTime(timezone=True), nullable=True)
    execution_notes = Column(Text, nullable=True)
    
    # Prompt tracking (for traceability)
    prompt_template_id = Column(Integer, ForeignKey("prompt_templates.id", ondelete="SET NULL"), nullable=True)
    prompt_version = Column(Integer, nullable=True)
    prompt_type = Column(String(50), nullable=True)  # analysis_daily, analysis_weekly, consolidation
    
    # Outcome tracking (for performance metrics)
    outcome = Column(String(20), nullable=True)  # win, loss, pending, cancelled
    actual_r_multiple = Column(Float, nullable=True)  # Realized R-multiple
    profit_loss = Column(Float, nullable=True)  # Realized P/L
    exit_price = Column(Float, nullable=True)
    exit_time = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    strategy = relationship("Strategy")
    prompt_template = relationship("PromptTemplate")
    orders = relationship("Order", back_populates="signal")
    
    # Indexes
    __table_args__ = (
        # Index for querying active signals by symbol
        # Index for finding signals by strategy
        # Index for time-based queries
    )
    
    def __repr__(self):
        return f"<TradingSignal(id={self.id}, symbol={self.symbol}, signal={self.signal_type}, confidence={self.confidence:.2f if self.confidence else 0})>"
    
    def to_dict(self):
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "symbol": self.symbol,
            "strategy_id": self.strategy_id,
            "signal_type": self.signal_type,
            "trend": self.trend,
            "confidence": self.confidence,
            "timeframe_primary": self.timeframe_primary,
            "timeframe_confirmation": self.timeframe_confirmation,
            "entry_price_low": self.entry_price_low,
            "entry_price_high": self.entry_price_high,
            "stop_loss": self.stop_loss,
            "target_conservative": self.target_conservative,
            "target_aggressive": self.target_aggressive,
            "r_multiple_conservative": self.r_multiple_conservative,
            "r_multiple_aggressive": self.r_multiple_aggressive,
            "position_size_percent": self.position_size_percent,
            "confirmation_signals": self.confirmation_signals,
            "analysis_daily": self.analysis_daily,
            "analysis_weekly": self.analysis_weekly,
            "analysis_consolidated": self.analysis_consolidated,
            "chart_url_daily": self.chart_url_daily,
            "chart_url_weekly": self.chart_url_weekly,
            "chart_html_daily": self.chart_html_daily,
            "chart_html_weekly": self.chart_html_weekly,
            "language": self.language,
            "model_used": self.model_used,
            "provider": self.provider,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "status": self.status,
            "execution_price": self.execution_price,
            "execution_time": self.execution_time.isoformat() if self.execution_time else None,
            # Prompt tracking
            "prompt_template_id": self.prompt_template_id,
            "prompt_version": self.prompt_version,
            "prompt_type": self.prompt_type,
            # Outcome tracking
            "outcome": self.outcome,
            "actual_r_multiple": self.actual_r_multiple,
            "profit_loss": self.profit_loss,
            "exit_price": self.exit_price,
            "exit_time": self.exit_time.isoformat() if self.exit_time else None,
        }
    
    @property
    def is_active(self):
        """Check if signal is still active."""
        from datetime import datetime
        return (
            self.status == "active" and
            (self.expires_at is None or self.expires_at > datetime.now())
        )
    
    @property
    def is_buyable(self):
        """Check if signal suggests buying."""
        return self.signal_type == "BUY" and self.is_active
    
    @property
    def is_sellable(self):
        """Check if signal suggests selling."""
        return self.signal_type == "SELL" and self.is_active

